version: '2'
services:
  dataserver:
    build: .
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong!Passw0rd>"
    ports:
      - "1433:1433"
    volumes:
      - ./Horizon.bak:/var/opt/mssql/data/Horizon.bak
      - ./kimbo_caterease.bak:/var/opt/mssql/data/kimbo_caterease.bak
      - ./entrypoint.sh:/bin/entrypoint.sh
      - ./data-setup.sh:/bin/data-setup.sh
    command: bin/data-setup.sh
