version: '2'
services:
  dataserver:
    build: .
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong!Passw0rd>"
    ports:
      - "1433:1433"
    volumes:
        - ./exampledb.bak:/var/backups/exampledb.bak
        - ./entrypoint.sh:/bin/entrypoint.sh
        - ./data-setup.sh:/bin/data-setup.sh
    command: bash -c "chmod +x /bin/entrypoint.sh && /bin/entrypoint.sh"
